name: Docker Image CI

on:
    push:
        branches: ['main', 'master', 'trunk']
        tags: ['v*']

jobs:
    build-push:
        if: ${{ github.event_name != 'pull_request' }}

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKERHUB_TEMPLATE }}

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}, ${{ secrets.DOCKERHUB_TEMPLATE }}:latest
                  labels: ${{ steps.meta.outputs.labels }}
